// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// InventoryNodesGetRequest inventory nodes get request
// swagger:model inventoryNodesGetRequest
type InventoryNodesGetRequest struct {

	// Unique node identifier.
	ID int64 `json:"id,omitempty"`
}

// Validate validates this inventory nodes get request
func (m *InventoryNodesGetRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryNodesGetRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryNodesGetRequest) UnmarshalBinary(b []byte) error {
	var res InventoryNodesGetRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
