// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InventoryNodesGetResponse inventory nodes get response
// swagger:model inventoryNodesGetResponse
type InventoryNodesGetResponse struct {

	// bare metal
	BareMetal *InventoryBareMetalNode `json:"bare_metal,omitempty"`

	// container
	Container *InventoryContainerNode `json:"container,omitempty"`

	// node
	Node *InventoryNode `json:"node,omitempty"`
}

// Validate validates this inventory nodes get response
func (m *InventoryNodesGetResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBareMetal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateContainer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryNodesGetResponse) validateBareMetal(formats strfmt.Registry) error {

	if swag.IsZero(m.BareMetal) { // not required
		return nil
	}

	if m.BareMetal != nil {
		if err := m.BareMetal.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("bare_metal")
			}
			return err
		}
	}

	return nil
}

func (m *InventoryNodesGetResponse) validateContainer(formats strfmt.Registry) error {

	if swag.IsZero(m.Container) { // not required
		return nil
	}

	if m.Container != nil {
		if err := m.Container.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("container")
			}
			return err
		}
	}

	return nil
}

func (m *InventoryNodesGetResponse) validateNode(formats strfmt.Registry) error {

	if swag.IsZero(m.Node) { // not required
		return nil
	}

	if m.Node != nil {
		if err := m.Node.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryNodesGetResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryNodesGetResponse) UnmarshalBinary(b []byte) error {
	var res InventoryNodesGetResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
