// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InventoryNodesListResponse inventory nodes list response
// swagger:model inventoryNodesListResponse
type InventoryNodesListResponse struct {

	// bare metal
	BareMetal []*InventoryBareMetalNode `json:"bare_metal"`

	// container
	Container []*InventoryContainerNode `json:"container"`

	// node
	Node []*InventoryNode `json:"node"`
}

// Validate validates this inventory nodes list response
func (m *InventoryNodesListResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBareMetal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateContainer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryNodesListResponse) validateBareMetal(formats strfmt.Registry) error {

	if swag.IsZero(m.BareMetal) { // not required
		return nil
	}

	for i := 0; i < len(m.BareMetal); i++ {
		if swag.IsZero(m.BareMetal[i]) { // not required
			continue
		}

		if m.BareMetal[i] != nil {
			if err := m.BareMetal[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("bare_metal" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *InventoryNodesListResponse) validateContainer(formats strfmt.Registry) error {

	if swag.IsZero(m.Container) { // not required
		return nil
	}

	for i := 0; i < len(m.Container); i++ {
		if swag.IsZero(m.Container[i]) { // not required
			continue
		}

		if m.Container[i] != nil {
			if err := m.Container[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("container" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *InventoryNodesListResponse) validateNode(formats strfmt.Registry) error {

	if swag.IsZero(m.Node) { // not required
		return nil
	}

	for i := 0; i < len(m.Node); i++ {
		if swag.IsZero(m.Node[i]) { // not required
			continue
		}

		if m.Node[i] != nil {
			if err := m.Node[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("node" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryNodesListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryNodesListResponse) UnmarshalBinary(b []byte) error {
	var res InventoryNodesListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
