language: go

go:
  - 1.11.x

before_install:
  # install binary protoc release
  - curl -L https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip -o ~/protoc.zip
  - unzip -q ~/protoc.zip -d ~
  - sudo install -d /usr/local/include/google/protobuf/compiler
  - sudo install -m 755 ~/bin/protoc /usr/local/bin/
  - sudo install -m 644 ~/include/google/protobuf/*.proto /usr/local/include/google/protobuf/
  - sudo install -m 644 ~/include/google/protobuf/compiler/*.proto /usr/local/include/google/protobuf/compiler/
  - protoc --version

before_script:
  # ensure that Gopkg.lock is up-to-date
  - curl -L https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o ~/dep
  - chmod +x ~/dep
  - ~/dep ensure -v
  - ~/dep check

script:
  - make init gen

  # check that generated files are up-to-date
  - git status
  - git diff --exit-code
