// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/gateway.proto

/*
Package gateway is a generated protocol buffer package.

It is generated from these files:
	gateway/gateway.proto

It has these top-level messages:
	CreateTunnelRequest
	CreateTunnelResponse
	WriteToTunnelRequest
	WriteToTunnelResponse
*/
package gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateTunnelRequest struct {
	AgentUuid string `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid" json:"agent_uuid,omitempty"`
	Dial      string `protobuf:"bytes,2,opt,name=dial" json:"dial,omitempty"`
}

func (m *CreateTunnelRequest) Reset()                    { *m = CreateTunnelRequest{} }
func (m *CreateTunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTunnelRequest) ProtoMessage()               {}
func (*CreateTunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateTunnelRequest) GetAgentUuid() string {
	if m != nil {
		return m.AgentUuid
	}
	return ""
}

func (m *CreateTunnelRequest) GetDial() string {
	if m != nil {
		return m.Dial
	}
	return ""
}

type CreateTunnelResponse struct {
	Error  string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Listen string `protobuf:"bytes,2,opt,name=listen" json:"listen,omitempty"`
}

func (m *CreateTunnelResponse) Reset()                    { *m = CreateTunnelResponse{} }
func (m *CreateTunnelResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTunnelResponse) ProtoMessage()               {}
func (*CreateTunnelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateTunnelResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateTunnelResponse) GetListen() string {
	if m != nil {
		return m.Listen
	}
	return ""
}

type WriteToTunnelRequest struct {
	TunnelId string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId" json:"tunnel_id,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *WriteToTunnelRequest) Reset()                    { *m = WriteToTunnelRequest{} }
func (m *WriteToTunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteToTunnelRequest) ProtoMessage()               {}
func (*WriteToTunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *WriteToTunnelRequest) GetTunnelId() string {
	if m != nil {
		return m.TunnelId
	}
	return ""
}

func (m *WriteToTunnelRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WriteToTunnelResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *WriteToTunnelResponse) Reset()                    { *m = WriteToTunnelResponse{} }
func (m *WriteToTunnelResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteToTunnelResponse) ProtoMessage()               {}
func (*WriteToTunnelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WriteToTunnelResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateTunnelRequest)(nil), "gateway.CreateTunnelRequest")
	proto.RegisterType((*CreateTunnelResponse)(nil), "gateway.CreateTunnelResponse")
	proto.RegisterType((*WriteToTunnelRequest)(nil), "gateway.WriteToTunnelRequest")
	proto.RegisterType((*WriteToTunnelResponse)(nil), "gateway.WriteToTunnelResponse")
}

func init() { proto.RegisterFile("gateway/gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xa9, 0xe8, 0xae, 0x1d, 0xd6, 0xcb, 0xd8, 0x95, 0x65, 0x75, 0x45, 0x72, 0xf2, 0xe2,
	0x0a, 0xfa, 0x08, 0x0a, 0x2a, 0x82, 0x87, 0xba, 0xe2, 0x71, 0x89, 0x76, 0x28, 0x81, 0x92, 0xd4,
	0x64, 0xa2, 0xf8, 0x42, 0x3e, 0xa7, 0x90, 0xc4, 0x3f, 0x95, 0xd6, 0x53, 0x66, 0xbe, 0x2f, 0xfc,
	0xf2, 0xcd, 0x04, 0xa6, 0xb5, 0x64, 0x7a, 0x93, 0xef, 0xa7, 0xe9, 0x5c, 0xb6, 0xd6, 0xb0, 0xc1,
	0x71, 0x6a, 0xc5, 0x35, 0xec, 0x5e, 0x58, 0x92, 0x4c, 0x2b, 0xaf, 0x35, 0x35, 0x25, 0xbd, 0x78,
	0x72, 0x8c, 0x0b, 0x00, 0x59, 0x93, 0xe6, 0xb5, 0xf7, 0xaa, 0x9a, 0x65, 0x47, 0xd9, 0x71, 0x5e,
	0xe6, 0x41, 0x79, 0xf0, 0xaa, 0x42, 0x84, 0xcd, 0x4a, 0xc9, 0x66, 0xb6, 0x11, 0x8c, 0x50, 0x8b,
	0x4b, 0x28, 0xba, 0x24, 0xd7, 0x1a, 0xed, 0x08, 0x0b, 0xd8, 0x22, 0x6b, 0x8d, 0x4d, 0x94, 0xd8,
	0xe0, 0x1e, 0x8c, 0x1a, 0xe5, 0x98, 0x74, 0x62, 0xa4, 0x4e, 0x5c, 0x41, 0xf1, 0x68, 0x15, 0xd3,
	0xca, 0x74, 0x03, 0xed, 0x43, 0xce, 0x41, 0x58, 0x7f, 0xe7, 0xd9, 0x8e, 0xc2, 0x4d, 0x8c, 0x23,
	0x59, 0x06, 0xd4, 0xa4, 0x0c, 0xb5, 0x38, 0x81, 0xe9, 0x1f, 0xd0, 0x7f, 0x79, 0xce, 0x3e, 0x32,
	0x18, 0xdf, 0x93, 0x7d, 0x55, 0xcf, 0x84, 0xb7, 0x30, 0xf9, 0x3d, 0x09, 0x1e, 0x2c, 0xbf, 0x96,
	0xd7, 0xb3, 0xaa, 0xf9, 0x62, 0xc0, 0x4d, 0xcf, 0xdd, 0xc1, 0x4e, 0x27, 0x07, 0xfe, 0xdc, 0xef,
	0x1b, 0x74, 0x7e, 0x38, 0x64, 0x47, 0xde, 0xd3, 0x28, 0x7c, 0xe0, 0xf9, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2f, 0x53, 0x47, 0x90, 0xd9, 0x01, 0x00, 0x00,
}
