// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/gateway.proto

/*
Package gateway is a generated protocol buffer package.

It is generated from these files:
	gateway/gateway.proto

It has these top-level messages:
	CreateTunnelRequest
	CreateTunnelResponse
*/
package gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateTunnelRequest struct {
	AgentUuid string `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid" json:"agent_uuid,omitempty"`
}

func (m *CreateTunnelRequest) Reset()                    { *m = CreateTunnelRequest{} }
func (m *CreateTunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTunnelRequest) ProtoMessage()               {}
func (*CreateTunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateTunnelRequest) GetAgentUuid() string {
	if m != nil {
		return m.AgentUuid
	}
	return ""
}

type CreateTunnelResponse struct {
}

func (m *CreateTunnelResponse) Reset()                    { *m = CreateTunnelResponse{} }
func (m *CreateTunnelResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTunnelResponse) ProtoMessage()               {}
func (*CreateTunnelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*CreateTunnelRequest)(nil), "gateway.CreateTunnelRequest")
	proto.RegisterType((*CreateTunnelResponse)(nil), "gateway.CreateTunnelResponse")
}

func init() { proto.RegisterFile("gateway/gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x4f, 0x2c, 0x49,
	0x2d, 0x4f, 0xac, 0xd4, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x92, 0x09, 0x97, 0xb0, 0x73, 0x51, 0x6a, 0x62, 0x49, 0x6a, 0x48, 0x69, 0x5e, 0x5e, 0x6a, 0x4e,
	0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x2c, 0x17, 0x57, 0x62, 0x7a, 0x6a, 0x5e, 0x49,
	0x7c, 0x69, 0x69, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x27, 0x58, 0x24, 0xb4,
	0x34, 0x33, 0x45, 0x49, 0x8c, 0x4b, 0x04, 0x55, 0x57, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x51,
	0x18, 0x17, 0x7b, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x37, 0x17, 0x0f, 0xb2, 0x12,
	0x21, 0x19, 0x3d, 0x98, 0x0b, 0xb0, 0xd8, 0x27, 0x25, 0x8b, 0x43, 0x16, 0x62, 0x6e, 0x12, 0x1b,
	0xd8, 0xd5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0xe5, 0xe3, 0x9f, 0xce, 0x00, 0x00,
	0x00,
}
