// Code generated by go-swagger; DO NOT EDIT.

package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	models "github.com/Percona-Lab/pmm-api/swagger/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewRemoveBareMetalParams creates a new RemoveBareMetalParams object
// with the default values initialized.
func NewRemoveBareMetalParams() *RemoveBareMetalParams {
	var ()
	return &RemoveBareMetalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveBareMetalParamsWithTimeout creates a new RemoveBareMetalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveBareMetalParamsWithTimeout(timeout time.Duration) *RemoveBareMetalParams {
	var ()
	return &RemoveBareMetalParams{

		timeout: timeout,
	}
}

// NewRemoveBareMetalParamsWithContext creates a new RemoveBareMetalParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveBareMetalParamsWithContext(ctx context.Context) *RemoveBareMetalParams {
	var ()
	return &RemoveBareMetalParams{

		Context: ctx,
	}
}

// NewRemoveBareMetalParamsWithHTTPClient creates a new RemoveBareMetalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveBareMetalParamsWithHTTPClient(client *http.Client) *RemoveBareMetalParams {
	var ()
	return &RemoveBareMetalParams{
		HTTPClient: client,
	}
}

/*RemoveBareMetalParams contains all the parameters to send to the API endpoint
for the remove bare metal operation typically these are written to a http.Request
*/
type RemoveBareMetalParams struct {

	/*Body*/
	Body *models.InventoryRemoveBareMetalNodeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove bare metal params
func (o *RemoveBareMetalParams) WithTimeout(timeout time.Duration) *RemoveBareMetalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove bare metal params
func (o *RemoveBareMetalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove bare metal params
func (o *RemoveBareMetalParams) WithContext(ctx context.Context) *RemoveBareMetalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove bare metal params
func (o *RemoveBareMetalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove bare metal params
func (o *RemoveBareMetalParams) WithHTTPClient(client *http.Client) *RemoveBareMetalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove bare metal params
func (o *RemoveBareMetalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remove bare metal params
func (o *RemoveBareMetalParams) WithBody(body *models.InventoryRemoveBareMetalNodeRequest) *RemoveBareMetalParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remove bare metal params
func (o *RemoveBareMetalParams) SetBody(body *models.InventoryRemoveBareMetalNodeRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveBareMetalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
