// Code generated by go-swagger; DO NOT EDIT.

package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	models "github.com/Percona-Lab/pmm-api/swagger/models"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// RemoveBareMetalReader is a Reader for the RemoveBareMetal structure.
type RemoveBareMetalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveBareMetalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRemoveBareMetalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveBareMetalOK creates a RemoveBareMetalOK with default headers values
func NewRemoveBareMetalOK() *RemoveBareMetalOK {
	return &RemoveBareMetalOK{}
}

/*RemoveBareMetalOK handles this case with default header values.

(empty)
*/
type RemoveBareMetalOK struct {
	Payload models.InventoryRemoveBareMetalNodeResponse
}

func (o *RemoveBareMetalOK) Error() string {
	return fmt.Sprintf("[POST /v0/inventory/Nodes/RemoveBareMetal][%d] removeBareMetalOK  %+v", 200, o.Payload)
}

func (o *RemoveBareMetalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
