// Code generated by protoc-gen-go. DO NOT EDIT.
// source: managed/tunnels.proto

/*
Package managed is a generated protocol buffer package.

It is generated from these files:
	managed/tunnels.proto

It has these top-level messages:
	TunnelsCreateRequest
	TunnelsCreateResponse
	TunnelsDeleteRequest
	TunnelsDeleteResponse
*/
package managed

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TunnelsCreateRequest struct {
	AgentUuid string `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid" json:"agent_uuid,omitempty"`
	Dial      string `protobuf:"bytes,2,opt,name=dial" json:"dial,omitempty"`
}

func (m *TunnelsCreateRequest) Reset()                    { *m = TunnelsCreateRequest{} }
func (m *TunnelsCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*TunnelsCreateRequest) ProtoMessage()               {}
func (*TunnelsCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TunnelsCreateRequest) GetAgentUuid() string {
	if m != nil {
		return m.AgentUuid
	}
	return ""
}

func (m *TunnelsCreateRequest) GetDial() string {
	if m != nil {
		return m.Dial
	}
	return ""
}

type TunnelsCreateResponse struct {
	Error  string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Listen string `protobuf:"bytes,2,opt,name=listen" json:"listen,omitempty"`
}

func (m *TunnelsCreateResponse) Reset()                    { *m = TunnelsCreateResponse{} }
func (m *TunnelsCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*TunnelsCreateResponse) ProtoMessage()               {}
func (*TunnelsCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TunnelsCreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TunnelsCreateResponse) GetListen() string {
	if m != nil {
		return m.Listen
	}
	return ""
}

type TunnelsDeleteRequest struct {
	Listen string `protobuf:"bytes,1,opt,name=listen" json:"listen,omitempty"`
}

func (m *TunnelsDeleteRequest) Reset()                    { *m = TunnelsDeleteRequest{} }
func (m *TunnelsDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*TunnelsDeleteRequest) ProtoMessage()               {}
func (*TunnelsDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TunnelsDeleteRequest) GetListen() string {
	if m != nil {
		return m.Listen
	}
	return ""
}

type TunnelsDeleteResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *TunnelsDeleteResponse) Reset()                    { *m = TunnelsDeleteResponse{} }
func (m *TunnelsDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*TunnelsDeleteResponse) ProtoMessage()               {}
func (*TunnelsDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TunnelsDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*TunnelsCreateRequest)(nil), "managed.TunnelsCreateRequest")
	proto.RegisterType((*TunnelsCreateResponse)(nil), "managed.TunnelsCreateResponse")
	proto.RegisterType((*TunnelsDeleteRequest)(nil), "managed.TunnelsDeleteRequest")
	proto.RegisterType((*TunnelsDeleteResponse)(nil), "managed.TunnelsDeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Tunnels service

type TunnelsClient interface {
	Create(ctx context.Context, in *TunnelsCreateRequest, opts ...grpc.CallOption) (*TunnelsCreateResponse, error)
	Delete(ctx context.Context, in *TunnelsDeleteRequest, opts ...grpc.CallOption) (*TunnelsDeleteResponse, error)
}

type tunnelsClient struct {
	cc *grpc.ClientConn
}

func NewTunnelsClient(cc *grpc.ClientConn) TunnelsClient {
	return &tunnelsClient{cc}
}

func (c *tunnelsClient) Create(ctx context.Context, in *TunnelsCreateRequest, opts ...grpc.CallOption) (*TunnelsCreateResponse, error) {
	out := new(TunnelsCreateResponse)
	err := grpc.Invoke(ctx, "/managed.Tunnels/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelsClient) Delete(ctx context.Context, in *TunnelsDeleteRequest, opts ...grpc.CallOption) (*TunnelsDeleteResponse, error) {
	out := new(TunnelsDeleteResponse)
	err := grpc.Invoke(ctx, "/managed.Tunnels/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tunnels service

type TunnelsServer interface {
	Create(context.Context, *TunnelsCreateRequest) (*TunnelsCreateResponse, error)
	Delete(context.Context, *TunnelsDeleteRequest) (*TunnelsDeleteResponse, error)
}

func RegisterTunnelsServer(s *grpc.Server, srv TunnelsServer) {
	s.RegisterService(&_Tunnels_serviceDesc, srv)
}

func _Tunnels_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/managed.Tunnels/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelsServer).Create(ctx, req.(*TunnelsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tunnels_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/managed.Tunnels/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelsServer).Delete(ctx, req.(*TunnelsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tunnels_serviceDesc = grpc.ServiceDesc{
	ServiceName: "managed.Tunnels",
	HandlerType: (*TunnelsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Tunnels_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Tunnels_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "managed/tunnels.proto",
}

func init() { proto.RegisterFile("managed/tunnels.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x89, 0x68, 0x96, 0x9d, 0xe3, 0xb0, 0x2b, 0x8b, 0x50, 0x91, 0x9e, 0xbc, 0x18, 0x41,
	0x3f, 0x82, 0x4a, 0xf1, 0x5a, 0xf4, 0x2c, 0x91, 0x0c, 0x25, 0x10, 0x93, 0x9a, 0x3f, 0x9f, 0xc6,
	0x2f, 0x2b, 0x24, 0xb1, 0xa5, 0x56, 0xf7, 0xd6, 0x99, 0xf7, 0xf8, 0xbd, 0xd7, 0x09, 0xec, 0x3f,
	0xa4, 0x95, 0x03, 0xa9, 0xdb, 0x98, 0xac, 0x25, 0x13, 0xc4, 0xe8, 0x5d, 0x74, 0xb8, 0xa9, 0xeb,
	0xf6, 0x19, 0x76, 0x2f, 0x45, 0x79, 0xf0, 0x24, 0x23, 0xf5, 0xf4, 0x99, 0x28, 0x44, 0x6c, 0x00,
	0xe4, 0x40, 0x36, 0xbe, 0xa5, 0xa4, 0xd5, 0x81, 0x5d, 0xb1, 0xeb, 0x6d, 0xbf, 0xcd, 0x9b, 0xd7,
	0xa4, 0x15, 0x22, 0x9c, 0x2a, 0x2d, 0xcd, 0xe1, 0x24, 0x0b, 0xf9, 0xbb, 0x7d, 0x82, 0xfd, 0x2f,
	0x54, 0x18, 0x9d, 0x0d, 0x84, 0x3b, 0x38, 0x23, 0xef, 0x9d, 0xaf, 0x98, 0x32, 0xe0, 0x39, 0x70,
	0xa3, 0x43, 0x24, 0x5b, 0x21, 0x75, 0x6a, 0xc5, 0xd4, 0xe8, 0x91, 0x0c, 0xcd, 0x8d, 0x66, 0x3f,
	0x5b, 0xf8, 0x6f, 0xa6, 0xd8, 0x1f, 0xff, 0xb1, 0xd8, 0xbb, 0x2f, 0x06, 0x9b, 0xea, 0xc7, 0x0e,
	0x78, 0xa9, 0x8a, 0x8d, 0xa8, 0x07, 0x11, 0x7f, 0x5d, 0xe3, 0xe2, 0xf2, 0x3f, 0xb9, 0x46, 0x75,
	0xc0, 0x4b, 0xf8, 0x1a, 0xb4, 0xf8, 0x89, 0x35, 0x68, 0xd9, 0xf9, 0x9d, 0xe7, 0xe7, 0xb9, 0xff,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x78, 0xd7, 0x13, 0xb7, 0x01, 0x00, 0x00,
}
