// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory/agents.proto

package inventory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MySQLdExporter struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RunsOnNodeId         uint32   `protobuf:"varint,2,opt,name=runs_on_node_id,json=runsOnNodeId,proto3" json:"runs_on_node_id,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ListenPort           uint32   `protobuf:"varint,5,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MySQLdExporter) Reset()         { *m = MySQLdExporter{} }
func (m *MySQLdExporter) String() string { return proto.CompactTextString(m) }
func (*MySQLdExporter) ProtoMessage()    {}
func (*MySQLdExporter) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_75bbb3a8beedecce, []int{0}
}
func (m *MySQLdExporter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MySQLdExporter.Unmarshal(m, b)
}
func (m *MySQLdExporter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MySQLdExporter.Marshal(b, m, deterministic)
}
func (dst *MySQLdExporter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MySQLdExporter.Merge(dst, src)
}
func (m *MySQLdExporter) XXX_Size() int {
	return xxx_messageInfo_MySQLdExporter.Size(m)
}
func (m *MySQLdExporter) XXX_DiscardUnknown() {
	xxx_messageInfo_MySQLdExporter.DiscardUnknown(m)
}

var xxx_messageInfo_MySQLdExporter proto.InternalMessageInfo

func (m *MySQLdExporter) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MySQLdExporter) GetRunsOnNodeId() uint32 {
	if m != nil {
		return m.RunsOnNodeId
	}
	return 0
}

func (m *MySQLdExporter) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MySQLdExporter) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MySQLdExporter) GetListenPort() uint32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

type AddMySQLdExporterRequest struct {
	RunsOnNodeId         uint32   `protobuf:"varint,2,opt,name=runs_on_node_id,json=runsOnNodeId,proto3" json:"runs_on_node_id,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMySQLdExporterRequest) Reset()         { *m = AddMySQLdExporterRequest{} }
func (m *AddMySQLdExporterRequest) String() string { return proto.CompactTextString(m) }
func (*AddMySQLdExporterRequest) ProtoMessage()    {}
func (*AddMySQLdExporterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_75bbb3a8beedecce, []int{1}
}
func (m *AddMySQLdExporterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMySQLdExporterRequest.Unmarshal(m, b)
}
func (m *AddMySQLdExporterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMySQLdExporterRequest.Marshal(b, m, deterministic)
}
func (dst *AddMySQLdExporterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMySQLdExporterRequest.Merge(dst, src)
}
func (m *AddMySQLdExporterRequest) XXX_Size() int {
	return xxx_messageInfo_AddMySQLdExporterRequest.Size(m)
}
func (m *AddMySQLdExporterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMySQLdExporterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMySQLdExporterRequest proto.InternalMessageInfo

func (m *AddMySQLdExporterRequest) GetRunsOnNodeId() uint32 {
	if m != nil {
		return m.RunsOnNodeId
	}
	return 0
}

func (m *AddMySQLdExporterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddMySQLdExporterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AddMySQLdExporterResponse struct {
	Agent                *MySQLdExporter `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddMySQLdExporterResponse) Reset()         { *m = AddMySQLdExporterResponse{} }
func (m *AddMySQLdExporterResponse) String() string { return proto.CompactTextString(m) }
func (*AddMySQLdExporterResponse) ProtoMessage()    {}
func (*AddMySQLdExporterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_75bbb3a8beedecce, []int{2}
}
func (m *AddMySQLdExporterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMySQLdExporterResponse.Unmarshal(m, b)
}
func (m *AddMySQLdExporterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMySQLdExporterResponse.Marshal(b, m, deterministic)
}
func (dst *AddMySQLdExporterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMySQLdExporterResponse.Merge(dst, src)
}
func (m *AddMySQLdExporterResponse) XXX_Size() int {
	return xxx_messageInfo_AddMySQLdExporterResponse.Size(m)
}
func (m *AddMySQLdExporterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMySQLdExporterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMySQLdExporterResponse proto.InternalMessageInfo

func (m *AddMySQLdExporterResponse) GetAgent() *MySQLdExporter {
	if m != nil {
		return m.Agent
	}
	return nil
}

func init() {
	proto.RegisterType((*MySQLdExporter)(nil), "inventory.MySQLdExporter")
	proto.RegisterType((*AddMySQLdExporterRequest)(nil), "inventory.AddMySQLdExporterRequest")
	proto.RegisterType((*AddMySQLdExporterResponse)(nil), "inventory.AddMySQLdExporterResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentsClient is the client API for Agents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentsClient interface {
	AddMySQLdExporter(ctx context.Context, in *AddMySQLdExporterRequest, opts ...grpc.CallOption) (*AddMySQLdExporterResponse, error)
}

type agentsClient struct {
	cc *grpc.ClientConn
}

func NewAgentsClient(cc *grpc.ClientConn) AgentsClient {
	return &agentsClient{cc}
}

func (c *agentsClient) AddMySQLdExporter(ctx context.Context, in *AddMySQLdExporterRequest, opts ...grpc.CallOption) (*AddMySQLdExporterResponse, error) {
	out := new(AddMySQLdExporterResponse)
	err := c.cc.Invoke(ctx, "/inventory.Agents/AddMySQLdExporter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentsServer is the server API for Agents service.
type AgentsServer interface {
	AddMySQLdExporter(context.Context, *AddMySQLdExporterRequest) (*AddMySQLdExporterResponse, error)
}

func RegisterAgentsServer(s *grpc.Server, srv AgentsServer) {
	s.RegisterService(&_Agents_serviceDesc, srv)
}

func _Agents_AddMySQLdExporter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMySQLdExporterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServer).AddMySQLdExporter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.Agents/AddMySQLdExporter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServer).AddMySQLdExporter(ctx, req.(*AddMySQLdExporterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agents_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.Agents",
	HandlerType: (*AgentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMySQLdExporter",
			Handler:    _Agents_AddMySQLdExporter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/agents.proto",
}

func init() { proto.RegisterFile("inventory/agents.proto", fileDescriptor_agents_75bbb3a8beedecce) }

var fileDescriptor_agents_75bbb3a8beedecce = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4d, 0x4a, 0x33, 0x41,
	0x10, 0xa5, 0xe7, 0xfb, 0x12, 0x4c, 0x45, 0x23, 0xf6, 0x42, 0x26, 0x41, 0x30, 0x8c, 0x3f, 0x04,
	0x85, 0xb4, 0xc6, 0x9d, 0xbb, 0x2c, 0x5c, 0x08, 0xf1, 0x2f, 0x1e, 0x60, 0x18, 0xe9, 0x22, 0x34,
	0xc4, 0xaa, 0xb1, 0xbb, 0x13, 0xcd, 0xd6, 0x1b, 0x88, 0x5b, 0x17, 0xde, 0xc9, 0x2b, 0x78, 0x10,
	0xc9, 0x8c, 0x8e, 0x3f, 0x51, 0x77, 0x2e, 0xab, 0xea, 0xd5, 0x7b, 0xaf, 0x5f, 0x17, 0x2c, 0x1b,
	0x1a, 0x23, 0x79, 0xb6, 0x13, 0x95, 0x0c, 0x90, 0xbc, 0x6b, 0xa7, 0x96, 0x3d, 0xcb, 0x4a, 0xd1,
	0x6f, 0xac, 0x0c, 0x98, 0x07, 0x43, 0x54, 0x49, 0x6a, 0x54, 0x42, 0xc4, 0x3e, 0xf1, 0x86, 0xe9,
	0x15, 0x18, 0x3d, 0x0a, 0xa8, 0x1d, 0x4d, 0xce, 0xcf, 0x7a, 0xfa, 0xe0, 0x26, 0x65, 0xeb, 0xd1,
	0xca, 0x1a, 0x04, 0x46, 0x87, 0xa2, 0x29, 0x5a, 0x0b, 0xfd, 0xc0, 0x68, 0xb9, 0x01, 0x8b, 0x76,
	0x44, 0x2e, 0x66, 0x8a, 0x89, 0x35, 0xc6, 0x46, 0x87, 0x41, 0x36, 0x9c, 0x9f, 0xb6, 0x4f, 0xe8,
	0x98, 0x35, 0x1e, 0x6a, 0xd9, 0x80, 0xb9, 0x91, 0x43, 0x4b, 0xc9, 0x25, 0x86, 0xff, 0x9a, 0xa2,
	0x55, 0xe9, 0x17, 0xf5, 0x74, 0x96, 0x26, 0xce, 0x5d, 0xb3, 0xd5, 0xe1, 0xff, 0x7c, 0xf6, 0x56,
	0xcb, 0x55, 0xa8, 0x0e, 0x8d, 0xf3, 0x48, 0xf1, 0x54, 0x3f, 0x2c, 0x65, 0xd4, 0x90, 0xb7, 0x4e,
	0xd9, 0xfa, 0x68, 0x02, 0x61, 0x57, 0xeb, 0xcf, 0x26, 0xfb, 0x78, 0x35, 0x42, 0xe7, 0xff, 0xd8,
	0x5b, 0xd4, 0x83, 0xfa, 0x37, 0xd2, 0x2e, 0x65, 0x72, 0x28, 0x15, 0x94, 0xb2, 0xcc, 0xb3, 0xa8,
	0xaa, 0x9d, 0x7a, 0xbb, 0xc8, 0xbc, 0xfd, 0x65, 0x23, 0xc7, 0x75, 0x1e, 0x04, 0x94, 0xbb, 0xd9,
	0x2f, 0xc9, 0x3b, 0x01, 0x4b, 0x33, 0xcc, 0x72, 0xed, 0x03, 0xc5, 0x4f, 0x4f, 0x6e, 0xac, 0xff,
	0x0e, 0xca, 0xcd, 0x45, 0xbb, 0xb7, 0x4f, 0xcf, 0xf7, 0xc1, 0x76, 0xb4, 0xa9, 0xc6, 0x3b, 0xea,
	0xfd, 0x48, 0x72, 0x79, 0x35, 0xb3, 0xb7, 0x2f, 0xb6, 0x2e, 0xca, 0xd9, 0x45, 0xec, 0xbd, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xae, 0x0f, 0xd2, 0xd2, 0x54, 0x02, 0x00, 0x00,
}
