// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory/agents.proto

package inventory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AgentType represents agent type.
type AgentType int32

const (
	AgentType_AGENT_TYPE_INVALID AgentType = 0
	AgentType_MYSQLD_EXPORTER    AgentType = 1
	AgentType_RDS_EXPORTER       AgentType = 2
)

var AgentType_name = map[int32]string{
	0: "AGENT_TYPE_INVALID",
	1: "MYSQLD_EXPORTER",
	2: "RDS_EXPORTER",
}
var AgentType_value = map[string]int32{
	"AGENT_TYPE_INVALID": 0,
	"MYSQLD_EXPORTER":    1,
	"RDS_EXPORTER":       2,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}
func (AgentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agents_054ef636fd8e0328, []int{0}
}

// AgentProcessStatus represents agent process state.
type AgentProcessStatus int32

const (
	AgentProcessStatus_AGENT_PROCESS_STATUS_INVALID AgentProcessStatus = 0
	AgentProcessStatus_RUNNING                      AgentProcessStatus = 1
)

var AgentProcessStatus_name = map[int32]string{
	0: "AGENT_PROCESS_STATUS_INVALID",
	1: "RUNNING",
}
var AgentProcessStatus_value = map[string]int32{
	"AGENT_PROCESS_STATUS_INVALID": 0,
	"RUNNING":                      1,
}

func (x AgentProcessStatus) String() string {
	return proto.EnumName(AgentProcessStatus_name, int32(x))
}
func (AgentProcessStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agents_054ef636fd8e0328, []int{1}
}

// MySQLdExporter represents mysqld_exporter configuration.
type MySQLdExporter struct {
	// Unique agent identifier.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Node identifier where agent runs.
	RunsOnNodeId uint32 `protobuf:"varint,2,opt,name=runs_on_node_id,json=runsOnNodeId,proto3" json:"runs_on_node_id,omitempty"`
	// MySQL username for extracting metrics.
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// MySQL password for extracting metrics.
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// HTTP listen port for exposing metrics.
	ListenPort           uint32   `protobuf:"varint,5,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MySQLdExporter) Reset()         { *m = MySQLdExporter{} }
func (m *MySQLdExporter) String() string { return proto.CompactTextString(m) }
func (*MySQLdExporter) ProtoMessage()    {}
func (*MySQLdExporter) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_054ef636fd8e0328, []int{0}
}
func (m *MySQLdExporter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MySQLdExporter.Unmarshal(m, b)
}
func (m *MySQLdExporter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MySQLdExporter.Marshal(b, m, deterministic)
}
func (dst *MySQLdExporter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MySQLdExporter.Merge(dst, src)
}
func (m *MySQLdExporter) XXX_Size() int {
	return xxx_messageInfo_MySQLdExporter.Size(m)
}
func (m *MySQLdExporter) XXX_DiscardUnknown() {
	xxx_messageInfo_MySQLdExporter.DiscardUnknown(m)
}

var xxx_messageInfo_MySQLdExporter proto.InternalMessageInfo

func (m *MySQLdExporter) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MySQLdExporter) GetRunsOnNodeId() uint32 {
	if m != nil {
		return m.RunsOnNodeId
	}
	return 0
}

func (m *MySQLdExporter) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MySQLdExporter) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MySQLdExporter) GetListenPort() uint32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

type AddMySQLdExporterRequest struct {
	// Node identifier where agent should run.
	RunsOnNodeId uint32 `protobuf:"varint,1,opt,name=runs_on_node_id,json=runsOnNodeId,proto3" json:"runs_on_node_id,omitempty"`
	// MySQL username for extracting metrics.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// MySQL password for extracting metrics.
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMySQLdExporterRequest) Reset()         { *m = AddMySQLdExporterRequest{} }
func (m *AddMySQLdExporterRequest) String() string { return proto.CompactTextString(m) }
func (*AddMySQLdExporterRequest) ProtoMessage()    {}
func (*AddMySQLdExporterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_054ef636fd8e0328, []int{1}
}
func (m *AddMySQLdExporterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMySQLdExporterRequest.Unmarshal(m, b)
}
func (m *AddMySQLdExporterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMySQLdExporterRequest.Marshal(b, m, deterministic)
}
func (dst *AddMySQLdExporterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMySQLdExporterRequest.Merge(dst, src)
}
func (m *AddMySQLdExporterRequest) XXX_Size() int {
	return xxx_messageInfo_AddMySQLdExporterRequest.Size(m)
}
func (m *AddMySQLdExporterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMySQLdExporterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMySQLdExporterRequest proto.InternalMessageInfo

func (m *AddMySQLdExporterRequest) GetRunsOnNodeId() uint32 {
	if m != nil {
		return m.RunsOnNodeId
	}
	return 0
}

func (m *AddMySQLdExporterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddMySQLdExporterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AddMySQLdExporterResponse struct {
	Agent                *MySQLdExporter `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddMySQLdExporterResponse) Reset()         { *m = AddMySQLdExporterResponse{} }
func (m *AddMySQLdExporterResponse) String() string { return proto.CompactTextString(m) }
func (*AddMySQLdExporterResponse) ProtoMessage()    {}
func (*AddMySQLdExporterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_054ef636fd8e0328, []int{2}
}
func (m *AddMySQLdExporterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMySQLdExporterResponse.Unmarshal(m, b)
}
func (m *AddMySQLdExporterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMySQLdExporterResponse.Marshal(b, m, deterministic)
}
func (dst *AddMySQLdExporterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMySQLdExporterResponse.Merge(dst, src)
}
func (m *AddMySQLdExporterResponse) XXX_Size() int {
	return xxx_messageInfo_AddMySQLdExporterResponse.Size(m)
}
func (m *AddMySQLdExporterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMySQLdExporterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMySQLdExporterResponse proto.InternalMessageInfo

func (m *AddMySQLdExporterResponse) GetAgent() *MySQLdExporter {
	if m != nil {
		return m.Agent
	}
	return nil
}

func init() {
	proto.RegisterType((*MySQLdExporter)(nil), "inventory.MySQLdExporter")
	proto.RegisterType((*AddMySQLdExporterRequest)(nil), "inventory.AddMySQLdExporterRequest")
	proto.RegisterType((*AddMySQLdExporterResponse)(nil), "inventory.AddMySQLdExporterResponse")
	proto.RegisterEnum("inventory.AgentType", AgentType_name, AgentType_value)
	proto.RegisterEnum("inventory.AgentProcessStatus", AgentProcessStatus_name, AgentProcessStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentsClient is the client API for Agents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentsClient interface {
	// AddMySQLdExporter adds mysqld_exporter agent.
	AddMySQLdExporter(ctx context.Context, in *AddMySQLdExporterRequest, opts ...grpc.CallOption) (*AddMySQLdExporterResponse, error)
}

type agentsClient struct {
	cc *grpc.ClientConn
}

func NewAgentsClient(cc *grpc.ClientConn) AgentsClient {
	return &agentsClient{cc}
}

func (c *agentsClient) AddMySQLdExporter(ctx context.Context, in *AddMySQLdExporterRequest, opts ...grpc.CallOption) (*AddMySQLdExporterResponse, error) {
	out := new(AddMySQLdExporterResponse)
	err := c.cc.Invoke(ctx, "/inventory.Agents/AddMySQLdExporter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentsServer is the server API for Agents service.
type AgentsServer interface {
	// AddMySQLdExporter adds mysqld_exporter agent.
	AddMySQLdExporter(context.Context, *AddMySQLdExporterRequest) (*AddMySQLdExporterResponse, error)
}

func RegisterAgentsServer(s *grpc.Server, srv AgentsServer) {
	s.RegisterService(&_Agents_serviceDesc, srv)
}

func _Agents_AddMySQLdExporter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMySQLdExporterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServer).AddMySQLdExporter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.Agents/AddMySQLdExporter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServer).AddMySQLdExporter(ctx, req.(*AddMySQLdExporterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agents_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.Agents",
	HandlerType: (*AgentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMySQLdExporter",
			Handler:    _Agents_AddMySQLdExporter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/agents.proto",
}

func init() { proto.RegisterFile("inventory/agents.proto", fileDescriptor_agents_054ef636fd8e0328) }

var fileDescriptor_agents_054ef636fd8e0328 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x29, 0x2d, 0xec, 0x6c, 0x69, 0x17, 0x23, 0x55, 0xe9, 0xaa, 0x12, 0xab, 0xf0, 0xa3,
	0x6a, 0x91, 0x36, 0x50, 0x6e, 0xdc, 0xa2, 0x6e, 0x54, 0x05, 0xa5, 0xd9, 0xd4, 0x4e, 0x11, 0x3d,
	0x59, 0x01, 0x5b, 0xab, 0x48, 0xc5, 0x0e, 0xb6, 0x53, 0xc8, 0x95, 0x37, 0x40, 0x5c, 0x39, 0xf0,
	0x4e, 0xbc, 0x02, 0x0f, 0x82, 0x92, 0xc0, 0xb6, 0xa5, 0x65, 0x7b, 0xf3, 0x7c, 0x33, 0xf3, 0x7d,
	0xdf, 0x8c, 0x07, 0xb6, 0x0a, 0x79, 0x26, 0xa4, 0x55, 0xba, 0xf6, 0xf3, 0xb9, 0x90, 0xd6, 0x4c,
	0x4a, 0xad, 0xac, 0xc2, 0xbd, 0x05, 0x3e, 0xdc, 0x99, 0x2b, 0x35, 0x3f, 0x15, 0x7e, 0x5e, 0x16,
	0x7e, 0x2e, 0xa5, 0xb2, 0xb9, 0x2d, 0x94, 0xfc, 0x53, 0xe8, 0xfd, 0x40, 0xb0, 0x71, 0x58, 0xd3,
	0xa3, 0x98, 0x87, 0x9f, 0x4b, 0xa5, 0xad, 0xd0, 0x78, 0x03, 0x9c, 0x82, 0xbb, 0x68, 0x84, 0x76,
	0xef, 0x11, 0xa7, 0xe0, 0xf8, 0x09, 0x6c, 0xea, 0x4a, 0x1a, 0xa6, 0x24, 0x93, 0x8a, 0x0b, 0x56,
	0x70, 0xd7, 0x69, 0x93, 0xeb, 0x0d, 0x3c, 0x93, 0x89, 0xe2, 0x22, 0xe2, 0x78, 0x08, 0x77, 0x2b,
	0x23, 0xb4, 0xcc, 0x3f, 0x08, 0x77, 0x65, 0x84, 0x76, 0x7b, 0x64, 0x11, 0x37, 0xb9, 0x32, 0x37,
	0xe6, 0x93, 0xd2, 0xdc, 0xbd, 0xdd, 0xe5, 0xfe, 0xc6, 0xf8, 0x21, 0xf4, 0x4f, 0x0b, 0x63, 0x85,
	0x64, 0x8d, 0xbe, 0xbb, 0xda, 0x52, 0x43, 0x07, 0xa5, 0x4a, 0x5b, 0xaf, 0x06, 0x37, 0xe0, 0xfc,
	0xb2, 0x49, 0x22, 0x3e, 0x56, 0xc2, 0xd8, 0xeb, 0xbc, 0xa1, 0x1b, 0xbc, 0x39, 0x4b, 0xbc, 0xad,
	0x5c, 0xf6, 0xe6, 0xc5, 0xb0, 0x7d, 0x8d, 0xb4, 0x29, 0x95, 0x34, 0x02, 0xfb, 0xb0, 0xda, 0xee,
	0xbc, 0x55, 0xec, 0xef, 0x6d, 0x4f, 0x16, 0x3b, 0x9f, 0xfc, 0xd3, 0xd1, 0xd5, 0x8d, 0x5f, 0x43,
	0x2f, 0x68, 0x1e, 0x59, 0x5d, 0x0a, 0xbc, 0x05, 0x38, 0x38, 0x08, 0x93, 0x8c, 0x65, 0x27, 0x69,
	0xc8, 0xa2, 0xe4, 0x4d, 0x10, 0x47, 0xd3, 0xc1, 0x2d, 0xfc, 0x00, 0x36, 0x0f, 0x4f, 0xe8, 0x51,
	0x3c, 0x65, 0xe1, 0xdb, 0x74, 0x46, 0xb2, 0x90, 0x0c, 0x10, 0x1e, 0xc0, 0x3a, 0x99, 0xd2, 0x73,
	0xc4, 0x19, 0xef, 0x03, 0x6e, 0xb9, 0x52, 0xad, 0xde, 0x0b, 0x63, 0xa8, 0xcd, 0x6d, 0x65, 0xf0,
	0x08, 0x76, 0x3a, 0xd2, 0x94, 0xcc, 0xf6, 0x43, 0x4a, 0x19, 0xcd, 0x82, 0xec, 0x98, 0x5e, 0xa0,
	0xef, 0xc3, 0x1d, 0x72, 0x9c, 0x24, 0x51, 0x72, 0x30, 0x40, 0x7b, 0xdf, 0x11, 0xac, 0xb5, 0x2c,
	0x06, 0x7f, 0x45, 0x70, 0xff, 0xca, 0xa8, 0xf8, 0xd1, 0x85, 0x99, 0xfe, 0xf7, 0x07, 0xc3, 0xc7,
	0xcb, 0x8b, 0xba, 0x6d, 0x79, 0x2f, 0xbe, 0xfc, 0xfc, 0xf5, 0xcd, 0x79, 0xe6, 0x3d, 0xf5, 0xcf,
	0x9e, 0xfb, 0xe7, 0x57, 0xdb, 0xc9, 0xfb, 0x57, 0xfa, 0x5e, 0xa1, 0xf1, 0xbb, 0xb5, 0xf6, 0x44,
	0x5f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x96, 0xee, 0x18, 0xcf, 0xe5, 0x02, 0x00, 0x00,
}
