// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory/nodes.proto

package inventory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BareMetalNode struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BareMetalNode) Reset()         { *m = BareMetalNode{} }
func (m *BareMetalNode) String() string { return proto.CompactTextString(m) }
func (*BareMetalNode) ProtoMessage()    {}
func (*BareMetalNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_e86615e95a674c7c, []int{0}
}
func (m *BareMetalNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BareMetalNode.Unmarshal(m, b)
}
func (m *BareMetalNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BareMetalNode.Marshal(b, m, deterministic)
}
func (dst *BareMetalNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BareMetalNode.Merge(dst, src)
}
func (m *BareMetalNode) XXX_Size() int {
	return xxx_messageInfo_BareMetalNode.Size(m)
}
func (m *BareMetalNode) XXX_DiscardUnknown() {
	xxx_messageInfo_BareMetalNode.DiscardUnknown(m)
}

var xxx_messageInfo_BareMetalNode proto.InternalMessageInfo

func (m *BareMetalNode) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BareMetalNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BareMetalNode) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type AddBareMetalNodeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBareMetalNodeRequest) Reset()         { *m = AddBareMetalNodeRequest{} }
func (m *AddBareMetalNodeRequest) String() string { return proto.CompactTextString(m) }
func (*AddBareMetalNodeRequest) ProtoMessage()    {}
func (*AddBareMetalNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_e86615e95a674c7c, []int{1}
}
func (m *AddBareMetalNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBareMetalNodeRequest.Unmarshal(m, b)
}
func (m *AddBareMetalNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBareMetalNodeRequest.Marshal(b, m, deterministic)
}
func (dst *AddBareMetalNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBareMetalNodeRequest.Merge(dst, src)
}
func (m *AddBareMetalNodeRequest) XXX_Size() int {
	return xxx_messageInfo_AddBareMetalNodeRequest.Size(m)
}
func (m *AddBareMetalNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBareMetalNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBareMetalNodeRequest proto.InternalMessageInfo

func (m *AddBareMetalNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddBareMetalNodeRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type AddBareMetalNodeResponse struct {
	Node                 *BareMetalNode `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddBareMetalNodeResponse) Reset()         { *m = AddBareMetalNodeResponse{} }
func (m *AddBareMetalNodeResponse) String() string { return proto.CompactTextString(m) }
func (*AddBareMetalNodeResponse) ProtoMessage()    {}
func (*AddBareMetalNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_e86615e95a674c7c, []int{2}
}
func (m *AddBareMetalNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBareMetalNodeResponse.Unmarshal(m, b)
}
func (m *AddBareMetalNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBareMetalNodeResponse.Marshal(b, m, deterministic)
}
func (dst *AddBareMetalNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBareMetalNodeResponse.Merge(dst, src)
}
func (m *AddBareMetalNodeResponse) XXX_Size() int {
	return xxx_messageInfo_AddBareMetalNodeResponse.Size(m)
}
func (m *AddBareMetalNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBareMetalNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBareMetalNodeResponse proto.InternalMessageInfo

func (m *AddBareMetalNodeResponse) GetNode() *BareMetalNode {
	if m != nil {
		return m.Node
	}
	return nil
}

type RemoveBareMetalNodeRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveBareMetalNodeRequest) Reset()         { *m = RemoveBareMetalNodeRequest{} }
func (m *RemoveBareMetalNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveBareMetalNodeRequest) ProtoMessage()    {}
func (*RemoveBareMetalNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_e86615e95a674c7c, []int{3}
}
func (m *RemoveBareMetalNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveBareMetalNodeRequest.Unmarshal(m, b)
}
func (m *RemoveBareMetalNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveBareMetalNodeRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveBareMetalNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveBareMetalNodeRequest.Merge(dst, src)
}
func (m *RemoveBareMetalNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveBareMetalNodeRequest.Size(m)
}
func (m *RemoveBareMetalNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveBareMetalNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveBareMetalNodeRequest proto.InternalMessageInfo

func (m *RemoveBareMetalNodeRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RemoveBareMetalNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveBareMetalNodeResponse) Reset()         { *m = RemoveBareMetalNodeResponse{} }
func (m *RemoveBareMetalNodeResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveBareMetalNodeResponse) ProtoMessage()    {}
func (*RemoveBareMetalNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_e86615e95a674c7c, []int{4}
}
func (m *RemoveBareMetalNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveBareMetalNodeResponse.Unmarshal(m, b)
}
func (m *RemoveBareMetalNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveBareMetalNodeResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveBareMetalNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveBareMetalNodeResponse.Merge(dst, src)
}
func (m *RemoveBareMetalNodeResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveBareMetalNodeResponse.Size(m)
}
func (m *RemoveBareMetalNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveBareMetalNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveBareMetalNodeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BareMetalNode)(nil), "inventory.BareMetalNode")
	proto.RegisterType((*AddBareMetalNodeRequest)(nil), "inventory.AddBareMetalNodeRequest")
	proto.RegisterType((*AddBareMetalNodeResponse)(nil), "inventory.AddBareMetalNodeResponse")
	proto.RegisterType((*RemoveBareMetalNodeRequest)(nil), "inventory.RemoveBareMetalNodeRequest")
	proto.RegisterType((*RemoveBareMetalNodeResponse)(nil), "inventory.RemoveBareMetalNodeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodesClient is the client API for Nodes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodesClient interface {
	AddBareMetal(ctx context.Context, in *AddBareMetalNodeRequest, opts ...grpc.CallOption) (*AddBareMetalNodeResponse, error)
	RemoveBareMetal(ctx context.Context, in *RemoveBareMetalNodeRequest, opts ...grpc.CallOption) (*RemoveBareMetalNodeResponse, error)
}

type nodesClient struct {
	cc *grpc.ClientConn
}

func NewNodesClient(cc *grpc.ClientConn) NodesClient {
	return &nodesClient{cc}
}

func (c *nodesClient) AddBareMetal(ctx context.Context, in *AddBareMetalNodeRequest, opts ...grpc.CallOption) (*AddBareMetalNodeResponse, error) {
	out := new(AddBareMetalNodeResponse)
	err := c.cc.Invoke(ctx, "/inventory.Nodes/AddBareMetal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesClient) RemoveBareMetal(ctx context.Context, in *RemoveBareMetalNodeRequest, opts ...grpc.CallOption) (*RemoveBareMetalNodeResponse, error) {
	out := new(RemoveBareMetalNodeResponse)
	err := c.cc.Invoke(ctx, "/inventory.Nodes/RemoveBareMetal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodesServer is the server API for Nodes service.
type NodesServer interface {
	AddBareMetal(context.Context, *AddBareMetalNodeRequest) (*AddBareMetalNodeResponse, error)
	RemoveBareMetal(context.Context, *RemoveBareMetalNodeRequest) (*RemoveBareMetalNodeResponse, error)
}

func RegisterNodesServer(s *grpc.Server, srv NodesServer) {
	s.RegisterService(&_Nodes_serviceDesc, srv)
}

func _Nodes_AddBareMetal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBareMetalNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServer).AddBareMetal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.Nodes/AddBareMetal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServer).AddBareMetal(ctx, req.(*AddBareMetalNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodes_RemoveBareMetal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBareMetalNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServer).RemoveBareMetal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.Nodes/RemoveBareMetal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServer).RemoveBareMetal(ctx, req.(*RemoveBareMetalNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nodes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.Nodes",
	HandlerType: (*NodesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBareMetal",
			Handler:    _Nodes_AddBareMetal_Handler,
		},
		{
			MethodName: "RemoveBareMetal",
			Handler:    _Nodes_RemoveBareMetal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/nodes.proto",
}

func init() { proto.RegisterFile("inventory/nodes.proto", fileDescriptor_nodes_e86615e95a674c7c) }

var fileDescriptor_nodes_e86615e95a674c7c = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xd1, 0x4a, 0xfb, 0x30,
	0x18, 0xc5, 0x49, 0xfe, 0xfb, 0x8b, 0xfb, 0x74, 0x0a, 0x01, 0xb1, 0x54, 0x85, 0x91, 0x31, 0x19,
	0x73, 0x34, 0x32, 0xef, 0x76, 0xa7, 0x57, 0x7a, 0xa1, 0x42, 0xdf, 0x20, 0x92, 0x8f, 0x59, 0xd8,
	0xf2, 0xcd, 0x25, 0x0e, 0xbc, 0x15, 0x1f, 0x40, 0xf0, 0x09, 0x7c, 0x26, 0x5f, 0xc1, 0x07, 0x91,
	0x65, 0xa3, 0x76, 0x75, 0xd5, 0xbb, 0xf6, 0x70, 0x72, 0xce, 0xef, 0xb4, 0x81, 0xbd, 0xcc, 0xce,
	0xd0, 0x7a, 0x9a, 0x3e, 0x29, 0x4b, 0x06, 0x5d, 0x32, 0x99, 0x92, 0x27, 0x51, 0xcf, 0xe5, 0xf8,
	0x70, 0x48, 0x34, 0x1c, 0xa1, 0xd2, 0x93, 0x4c, 0x69, 0x6b, 0xc9, 0x6b, 0x9f, 0x91, 0x5d, 0x1a,
	0xe5, 0x2d, 0x34, 0x2e, 0xf4, 0x14, 0xaf, 0xd1, 0xeb, 0xd1, 0x0d, 0x19, 0x14, 0x3b, 0xc0, 0x33,
	0x13, 0xb1, 0x26, 0xeb, 0x34, 0x52, 0x9e, 0x19, 0x21, 0xa0, 0x66, 0xf5, 0x18, 0x23, 0xde, 0x64,
	0x9d, 0x7a, 0x1a, 0x9e, 0x45, 0x0c, 0x9b, 0xf7, 0xe4, 0x7c, 0xd0, 0xff, 0x05, 0x3d, 0x7f, 0x97,
	0x57, 0xb0, 0x7f, 0x6e, 0xcc, 0x4a, 0x66, 0x8a, 0x0f, 0x8f, 0xe8, 0x7c, 0x1e, 0xc5, 0x2a, 0xa2,
	0x78, 0x29, 0xea, 0x12, 0xa2, 0x9f, 0x51, 0x6e, 0x42, 0xd6, 0xa1, 0xe8, 0x41, 0x6d, 0xbe, 0x37,
	0x64, 0x6d, 0xf5, 0xa3, 0x24, 0xdf, 0x9b, 0xac, 0xfa, 0x83, 0x4b, 0xf6, 0x20, 0x4e, 0x71, 0x4c,
	0x33, 0x5c, 0xcb, 0x55, 0x9a, 0x2c, 0x8f, 0xe0, 0x60, 0xad, 0x7b, 0x51, 0xdd, 0x7f, 0xe7, 0xf0,
	0x7f, 0x2e, 0x38, 0xf1, 0xc2, 0x60, 0xbb, 0x48, 0x28, 0x64, 0x81, 0xa3, 0xe2, 0x2b, 0xc4, 0xad,
	0x5f, 0x3d, 0x8b, 0x0e, 0x79, 0xf2, 0xfc, 0xf1, 0xf9, 0xc6, 0xdb, 0xb2, 0xa9, 0x66, 0xa7, 0xea,
	0xfb, 0x17, 0x87, 0x5a, 0x55, 0x3c, 0x35, 0x60, 0x5d, 0xf1, 0xca, 0x60, 0xb7, 0x04, 0x2c, 0xda,
	0x85, 0x96, 0xea, 0xe9, 0xf1, 0xf1, 0x5f, 0xb6, 0x25, 0x4f, 0x12, 0x78, 0x3a, 0xb2, 0xb5, 0x8e,
	0xa7, 0x74, 0x70, 0xc0, 0xba, 0x77, 0x1b, 0xe1, 0x76, 0x9d, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xbf, 0xdb, 0x94, 0xf2, 0x9f, 0x02, 0x00, 0x00,
}
