// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/inventory/nodes.proto

package inventory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeType int32

const (
	NodeType_NODE_TYPE_INVALID NodeType = 0
	NodeType_BARE_METAL        NodeType = 1
	NodeType_VIRTUAL_MACHINE   NodeType = 2
	NodeType_CONTAINER         NodeType = 3
	NodeType_REMOTE            NodeType = 8
	NodeType_REMOTE_RDS        NodeType = 9
)

var NodeType_name = map[int32]string{
	0: "NODE_TYPE_INVALID",
	1: "BARE_METAL",
	2: "VIRTUAL_MACHINE",
	3: "CONTAINER",
	8: "REMOTE",
	9: "REMOTE_RDS",
}
var NodeType_value = map[string]int32{
	"NODE_TYPE_INVALID": 0,
	"BARE_METAL":        1,
	"VIRTUAL_MACHINE":   2,
	"CONTAINER":         3,
	"REMOTE":            8,
	"REMOTE_RDS":        9,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nodes_80893461afcf35ed, []int{0}
}

type Node struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 NodeType `protobuf:"varint,2,opt,name=type,proto3,enum=inventory.NodeType" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_80893461afcf35ed, []int{0}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_NODE_TYPE_INVALID
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BareMetalNode struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 NodeType `protobuf:"varint,2,opt,name=type,proto3,enum=inventory.NodeType" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BareMetalNode) Reset()         { *m = BareMetalNode{} }
func (m *BareMetalNode) String() string { return proto.CompactTextString(m) }
func (*BareMetalNode) ProtoMessage()    {}
func (*BareMetalNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_80893461afcf35ed, []int{1}
}
func (m *BareMetalNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BareMetalNode.Unmarshal(m, b)
}
func (m *BareMetalNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BareMetalNode.Marshal(b, m, deterministic)
}
func (dst *BareMetalNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BareMetalNode.Merge(dst, src)
}
func (m *BareMetalNode) XXX_Size() int {
	return xxx_messageInfo_BareMetalNode.Size(m)
}
func (m *BareMetalNode) XXX_DiscardUnknown() {
	xxx_messageInfo_BareMetalNode.DiscardUnknown(m)
}

var xxx_messageInfo_BareMetalNode proto.InternalMessageInfo

func (m *BareMetalNode) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BareMetalNode) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_NODE_TYPE_INVALID
}

func (m *BareMetalNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type VirtualMachineNode struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 NodeType `protobuf:"varint,2,opt,name=type,proto3,enum=inventory.NodeType" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualMachineNode) Reset()         { *m = VirtualMachineNode{} }
func (m *VirtualMachineNode) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineNode) ProtoMessage()    {}
func (*VirtualMachineNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_80893461afcf35ed, []int{2}
}
func (m *VirtualMachineNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineNode.Unmarshal(m, b)
}
func (m *VirtualMachineNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineNode.Marshal(b, m, deterministic)
}
func (dst *VirtualMachineNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineNode.Merge(dst, src)
}
func (m *VirtualMachineNode) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineNode.Size(m)
}
func (m *VirtualMachineNode) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineNode.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineNode proto.InternalMessageInfo

func (m *VirtualMachineNode) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VirtualMachineNode) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_NODE_TYPE_INVALID
}

func (m *VirtualMachineNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ContainerNode struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 NodeType `protobuf:"varint,2,opt,name=type,proto3,enum=inventory.NodeType" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerNode) Reset()         { *m = ContainerNode{} }
func (m *ContainerNode) String() string { return proto.CompactTextString(m) }
func (*ContainerNode) ProtoMessage()    {}
func (*ContainerNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_80893461afcf35ed, []int{3}
}
func (m *ContainerNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerNode.Unmarshal(m, b)
}
func (m *ContainerNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerNode.Marshal(b, m, deterministic)
}
func (dst *ContainerNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerNode.Merge(dst, src)
}
func (m *ContainerNode) XXX_Size() int {
	return xxx_messageInfo_ContainerNode.Size(m)
}
func (m *ContainerNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerNode.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerNode proto.InternalMessageInfo

func (m *ContainerNode) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContainerNode) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_NODE_TYPE_INVALID
}

func (m *ContainerNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RemoteNode struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 NodeType `protobuf:"varint,2,opt,name=type,proto3,enum=inventory.NodeType" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteNode) Reset()         { *m = RemoteNode{} }
func (m *RemoteNode) String() string { return proto.CompactTextString(m) }
func (*RemoteNode) ProtoMessage()    {}
func (*RemoteNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_80893461afcf35ed, []int{4}
}
func (m *RemoteNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteNode.Unmarshal(m, b)
}
func (m *RemoteNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteNode.Marshal(b, m, deterministic)
}
func (dst *RemoteNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteNode.Merge(dst, src)
}
func (m *RemoteNode) XXX_Size() int {
	return xxx_messageInfo_RemoteNode.Size(m)
}
func (m *RemoteNode) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteNode.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteNode proto.InternalMessageInfo

func (m *RemoteNode) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RemoteNode) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_NODE_TYPE_INVALID
}

func (m *RemoteNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RemoteRDSNode struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 NodeType `protobuf:"varint,2,opt,name=type,proto3,enum=inventory.NodeType" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Region               string   `protobuf:"bytes,8,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteRDSNode) Reset()         { *m = RemoteRDSNode{} }
func (m *RemoteRDSNode) String() string { return proto.CompactTextString(m) }
func (*RemoteRDSNode) ProtoMessage()    {}
func (*RemoteRDSNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodes_80893461afcf35ed, []int{5}
}
func (m *RemoteRDSNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteRDSNode.Unmarshal(m, b)
}
func (m *RemoteRDSNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteRDSNode.Marshal(b, m, deterministic)
}
func (dst *RemoteRDSNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteRDSNode.Merge(dst, src)
}
func (m *RemoteRDSNode) XXX_Size() int {
	return xxx_messageInfo_RemoteRDSNode.Size(m)
}
func (m *RemoteRDSNode) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteRDSNode.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteRDSNode proto.InternalMessageInfo

func (m *RemoteRDSNode) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RemoteRDSNode) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_NODE_TYPE_INVALID
}

func (m *RemoteRDSNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoteRDSNode) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func init() {
	proto.RegisterType((*Node)(nil), "inventory.Node")
	proto.RegisterType((*BareMetalNode)(nil), "inventory.BareMetalNode")
	proto.RegisterType((*VirtualMachineNode)(nil), "inventory.VirtualMachineNode")
	proto.RegisterType((*ContainerNode)(nil), "inventory.ContainerNode")
	proto.RegisterType((*RemoteNode)(nil), "inventory.RemoteNode")
	proto.RegisterType((*RemoteRDSNode)(nil), "inventory.RemoteRDSNode")
	proto.RegisterEnum("inventory.NodeType", NodeType_name, NodeType_value)
}

func init() { proto.RegisterFile("proto/inventory/nodes.proto", fileDescriptor_nodes_80893461afcf35ed) }

var fileDescriptor_nodes_80893461afcf35ed = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xc1, 0x6a, 0xea, 0x40,
	0x18, 0x85, 0x6f, 0x62, 0x90, 0xe4, 0x07, 0xbd, 0x73, 0x47, 0x6e, 0x09, 0x6d, 0x17, 0xe2, 0xa6,
	0xd2, 0x85, 0x81, 0xf6, 0x09, 0xa2, 0x19, 0x68, 0x8a, 0x89, 0x65, 0x4c, 0x05, 0x57, 0x61, 0x6c,
	0x7e, 0xd2, 0x01, 0x9d, 0x49, 0xd3, 0x69, 0xc1, 0x3e, 0x7d, 0x31, 0x5a, 0x9f, 0xa0, 0xd9, 0x9d,
	0x39, 0x9c, 0x39, 0x1f, 0x07, 0x7e, 0xb8, 0xaa, 0x6a, 0x6d, 0x74, 0x20, 0xd5, 0x27, 0x2a, 0xa3,
	0xeb, 0x7d, 0xa0, 0x74, 0x81, 0xef, 0x93, 0xc6, 0xa5, 0xde, 0xd9, 0xbe, 0xbc, 0x2e, 0xb5, 0x2e,
	0xb7, 0x18, 0x88, 0x4a, 0x06, 0x42, 0x29, 0x6d, 0x84, 0x91, 0x5a, 0x9d, 0x82, 0xa3, 0x35, 0x38,
	0xa9, 0x2e, 0x90, 0xf6, 0xc1, 0x96, 0x85, 0x6f, 0x0d, 0xad, 0xb1, 0xc3, 0x6d, 0x59, 0xd0, 0x1b,
	0x70, 0xcc, 0xbe, 0x42, 0xdf, 0x1e, 0x5a, 0xe3, 0xfe, 0xdd, 0x60, 0x72, 0xee, 0x9b, 0x1c, 0xe2,
	0xd9, 0xbe, 0x42, 0xde, 0x04, 0x28, 0x05, 0x47, 0x89, 0x1d, 0xfa, 0x9d, 0xa1, 0x35, 0xf6, 0x78,
	0xa3, 0x1f, 0x1d, 0xd7, 0x21, 0xee, 0x68, 0x03, 0xbd, 0xa9, 0xa8, 0x31, 0x41, 0x23, 0xb6, 0x6d,
	0x31, 0x4a, 0xa0, 0x2b, 0x59, 0x9b, 0x0f, 0xb1, 0x4d, 0xc4, 0xcb, 0xab, 0x54, 0xd8, 0xe2, 0x98,
	0x99, 0x56, 0x46, 0x48, 0x85, 0x75, 0x5b, 0x8c, 0x1c, 0x80, 0xe3, 0x4e, 0x9b, 0xd6, 0x46, 0x7c,
	0x41, 0xef, 0x08, 0xe0, 0xd1, 0xf2, 0xd7, 0x19, 0xf4, 0x02, 0xba, 0x35, 0x96, 0x52, 0x2b, 0xdf,
	0x6d, 0xdc, 0xd3, 0xeb, 0xc8, 0xbe, 0x7d, 0x03, 0xf7, 0xa7, 0x83, 0xfe, 0x87, 0x7f, 0xe9, 0x22,
	0x62, 0x79, 0xb6, 0x7e, 0x62, 0x79, 0x9c, 0xae, 0xc2, 0x79, 0x1c, 0x91, 0x3f, 0xb4, 0x0f, 0x30,
	0x0d, 0x39, 0xcb, 0x13, 0x96, 0x85, 0x73, 0x62, 0xd1, 0x01, 0xfc, 0x5d, 0xc5, 0x3c, 0x7b, 0x0e,
	0xe7, 0x79, 0x12, 0xce, 0x1e, 0xe2, 0x94, 0x11, 0x9b, 0xf6, 0xc0, 0x9b, 0x2d, 0xd2, 0x2c, 0x8c,
	0x53, 0xc6, 0x49, 0x87, 0x02, 0x74, 0x39, 0x4b, 0x16, 0x19, 0x23, 0xee, 0xe1, 0xff, 0x51, 0xe7,
	0x3c, 0x5a, 0x12, 0x6f, 0xd3, 0x6d, 0x4e, 0xfc, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x35,
	0x91, 0x73, 0x2a, 0x03, 0x00, 0x00,
}
