// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	models "github.com/Percona-Lab/pmm-api/swagger/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewRemoveMySqldExporterParams creates a new RemoveMySqldExporterParams object
// with the default values initialized.
func NewRemoveMySqldExporterParams() *RemoveMySqldExporterParams {
	var ()
	return &RemoveMySqldExporterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveMySqldExporterParamsWithTimeout creates a new RemoveMySqldExporterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveMySqldExporterParamsWithTimeout(timeout time.Duration) *RemoveMySqldExporterParams {
	var ()
	return &RemoveMySqldExporterParams{

		timeout: timeout,
	}
}

// NewRemoveMySqldExporterParamsWithContext creates a new RemoveMySqldExporterParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveMySqldExporterParamsWithContext(ctx context.Context) *RemoveMySqldExporterParams {
	var ()
	return &RemoveMySqldExporterParams{

		Context: ctx,
	}
}

// NewRemoveMySqldExporterParamsWithHTTPClient creates a new RemoveMySqldExporterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveMySqldExporterParamsWithHTTPClient(client *http.Client) *RemoveMySqldExporterParams {
	var ()
	return &RemoveMySqldExporterParams{
		HTTPClient: client,
	}
}

/*RemoveMySqldExporterParams contains all the parameters to send to the API endpoint
for the remove my sqld exporter operation typically these are written to a http.Request
*/
type RemoveMySqldExporterParams struct {

	/*Body*/
	Body *models.InventoryRemoveMySqldExporterRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove my sqld exporter params
func (o *RemoveMySqldExporterParams) WithTimeout(timeout time.Duration) *RemoveMySqldExporterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove my sqld exporter params
func (o *RemoveMySqldExporterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove my sqld exporter params
func (o *RemoveMySqldExporterParams) WithContext(ctx context.Context) *RemoveMySqldExporterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove my sqld exporter params
func (o *RemoveMySqldExporterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove my sqld exporter params
func (o *RemoveMySqldExporterParams) WithHTTPClient(client *http.Client) *RemoveMySqldExporterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove my sqld exporter params
func (o *RemoveMySqldExporterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remove my sqld exporter params
func (o *RemoveMySqldExporterParams) WithBody(body *models.InventoryRemoveMySqldExporterRequest) *RemoveMySqldExporterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remove my sqld exporter params
func (o *RemoveMySqldExporterParams) SetBody(body *models.InventoryRemoveMySqldExporterRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveMySqldExporterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
