// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	models "github.com/Percona-Lab/pmm-api/swagger/models"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// RemoveMySqldExporterReader is a Reader for the RemoveMySqldExporter structure.
type RemoveMySqldExporterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveMySqldExporterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRemoveMySqldExporterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveMySqldExporterOK creates a RemoveMySqldExporterOK with default headers values
func NewRemoveMySqldExporterOK() *RemoveMySqldExporterOK {
	return &RemoveMySqldExporterOK{}
}

/*RemoveMySqldExporterOK handles this case with default header values.

(empty)
*/
type RemoveMySqldExporterOK struct {
	Payload models.InventoryRemoveMySqldExporterResponse
}

func (o *RemoveMySqldExporterOK) Error() string {
	return fmt.Sprintf("[POST /v0/inventory/Agents/RemoveMySQLdExporter][%d] removeMySqldExporterOK  %+v", 200, o.Payload)
}

func (o *RemoveMySqldExporterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
