// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryMySqldExporter inventory my sqld exporter
// swagger:model inventoryMySQLdExporter
type InventoryMySqldExporter struct {

	// id
	ID int64 `json:"id,omitempty"`

	// listen port
	ListenPort int64 `json:"listen_port,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// runs on node id
	RunsOnNodeID int64 `json:"runs_on_node_id,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this inventory my sqld exporter
func (m *InventoryMySqldExporter) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryMySqldExporter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryMySqldExporter) UnmarshalBinary(b []byte) error {
	var res InventoryMySqldExporter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
