// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryAddMySqldExporterRequest inventory add my sqld exporter request
// swagger:model inventoryAddMySQLdExporterRequest
type InventoryAddMySqldExporterRequest struct {

	// password
	Password string `json:"password,omitempty"`

	// runs on node id
	RunsOnNodeID int64 `json:"runs_on_node_id,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this inventory add my sqld exporter request
func (m *InventoryAddMySqldExporterRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryAddMySqldExporterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryAddMySqldExporterRequest) UnmarshalBinary(b []byte) error {
	var res InventoryAddMySqldExporterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
