// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryRemoveMySqldExporterRequest inventory remove my sqld exporter request
// swagger:model inventoryRemoveMySQLdExporterRequest
type InventoryRemoveMySqldExporterRequest struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this inventory remove my sqld exporter request
func (m *InventoryRemoveMySqldExporterRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InventoryRemoveMySqldExporterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryRemoveMySqldExporterRequest) UnmarshalBinary(b []byte) error {
	var res InventoryRemoveMySqldExporterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
