// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// InventoryAddMySqldExporterRequest inventory add my sqld exporter request
// swagger:model inventoryAddMySQLdExporterRequest
type InventoryAddMySqldExporterRequest interface{}
