// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent/agent.proto

/*
Package agent is a generated protocol buffer package.

It is generated from these files:
	agent/agent.proto

It has these top-level messages:
	CreateTunnelRequest
	CreateTunnelResponse
	WriteToTunnelRequest
	WriteToTunnelResponse
*/
package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateTunnelRequest struct {
	Dial string `protobuf:"bytes,1,opt,name=dial" json:"dial,omitempty"`
}

func (m *CreateTunnelRequest) Reset()                    { *m = CreateTunnelRequest{} }
func (m *CreateTunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTunnelRequest) ProtoMessage()               {}
func (*CreateTunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateTunnelRequest) GetDial() string {
	if m != nil {
		return m.Dial
	}
	return ""
}

type CreateTunnelResponse struct {
	TunnelId string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId" json:"tunnel_id,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *CreateTunnelResponse) Reset()                    { *m = CreateTunnelResponse{} }
func (m *CreateTunnelResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTunnelResponse) ProtoMessage()               {}
func (*CreateTunnelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateTunnelResponse) GetTunnelId() string {
	if m != nil {
		return m.TunnelId
	}
	return ""
}

func (m *CreateTunnelResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type WriteToTunnelRequest struct {
	TunnelId string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId" json:"tunnel_id,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *WriteToTunnelRequest) Reset()                    { *m = WriteToTunnelRequest{} }
func (m *WriteToTunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteToTunnelRequest) ProtoMessage()               {}
func (*WriteToTunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *WriteToTunnelRequest) GetTunnelId() string {
	if m != nil {
		return m.TunnelId
	}
	return ""
}

func (m *WriteToTunnelRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WriteToTunnelResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *WriteToTunnelResponse) Reset()                    { *m = WriteToTunnelResponse{} }
func (m *WriteToTunnelResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteToTunnelResponse) ProtoMessage()               {}
func (*WriteToTunnelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WriteToTunnelResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateTunnelRequest)(nil), "agent.CreateTunnelRequest")
	proto.RegisterType((*CreateTunnelResponse)(nil), "agent.CreateTunnelResponse")
	proto.RegisterType((*WriteToTunnelRequest)(nil), "agent.WriteToTunnelRequest")
	proto.RegisterType((*WriteToTunnelResponse)(nil), "agent.WriteToTunnelResponse")
}

func init() { proto.RegisterFile("agent/agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x26,
	0x97, 0xb0, 0x73, 0x51, 0x6a, 0x62, 0x49, 0x6a, 0x48, 0x69, 0x5e, 0x5e, 0x6a, 0x4e, 0x50, 0x6a,
	0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x10, 0x17, 0x4b, 0x4a, 0x66, 0x62, 0x8e, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xe4, 0xc9, 0x25, 0x82, 0xaa, 0xb4, 0xb8, 0x20, 0x3f, 0xaf,
	0x38, 0x55, 0x48, 0x9a, 0x8b, 0xb3, 0x04, 0x2c, 0x12, 0x9f, 0x99, 0x02, 0xd5, 0xc0, 0x01, 0x11,
	0xf0, 0x4c, 0x11, 0x12, 0xe1, 0x62, 0x4d, 0x2d, 0x2a, 0xca, 0x2f, 0x92, 0x60, 0x02, 0x4b, 0x40,
	0x38, 0x4a, 0xee, 0x5c, 0x22, 0xe1, 0x45, 0x99, 0x25, 0xa9, 0x21, 0xf9, 0xa8, 0xd6, 0xe2, 0x35,
	0x0a, 0xe4, 0xa6, 0xc4, 0x92, 0x44, 0xb0, 0x49, 0x3c, 0x41, 0x60, 0xb6, 0x92, 0x2e, 0x97, 0x28,
	0x9a, 0x41, 0x50, 0x47, 0xc1, 0xed, 0x65, 0x44, 0xb2, 0xd7, 0x68, 0x1e, 0x23, 0x17, 0x7b, 0x70,
	0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x3b, 0x17, 0x0f, 0xb2, 0x77, 0x84, 0xa4, 0xf4, 0x20,
	0xc1, 0x83, 0x25, 0x38, 0xa4, 0xa4, 0xb1, 0xca, 0x41, 0xad, 0xf2, 0xe2, 0xe2, 0x45, 0x71, 0x83,
	0x10, 0x4c, 0x35, 0x36, 0x2f, 0x4a, 0xc9, 0x60, 0x97, 0x84, 0x98, 0x95, 0xc4, 0x06, 0x8e, 0x1c,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x76, 0xfa, 0x6a, 0xb1, 0x01, 0x00, 0x00,
}
