// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent/agent.proto

package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{0}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

type RegisterResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{1}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ConnectRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{2}
}
func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (dst *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(dst, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ConnectRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ConnectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{3}
}
func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (dst *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(dst, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

type PingRequest struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{4}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type PingResponse struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{5}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (dst *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(dst, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type SetStateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStateRequest) Reset()         { *m = SetStateRequest{} }
func (m *SetStateRequest) String() string { return proto.CompactTextString(m) }
func (*SetStateRequest) ProtoMessage()    {}
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{6}
}
func (m *SetStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStateRequest.Unmarshal(m, b)
}
func (m *SetStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStateRequest.Marshal(b, m, deterministic)
}
func (dst *SetStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStateRequest.Merge(dst, src)
}
func (m *SetStateRequest) XXX_Size() int {
	return xxx_messageInfo_SetStateRequest.Size(m)
}
func (m *SetStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetStateRequest proto.InternalMessageInfo

type SetStateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStateResponse) Reset()         { *m = SetStateResponse{} }
func (m *SetStateResponse) String() string { return proto.CompactTextString(m) }
func (*SetStateResponse) ProtoMessage()    {}
func (*SetStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{7}
}
func (m *SetStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStateResponse.Unmarshal(m, b)
}
func (m *SetStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStateResponse.Marshal(b, m, deterministic)
}
func (dst *SetStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStateResponse.Merge(dst, src)
}
func (m *SetStateResponse) XXX_Size() int {
	return xxx_messageInfo_SetStateResponse.Size(m)
}
func (m *SetStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetStateResponse proto.InternalMessageInfo

type AgentMessage struct {
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*AgentMessage_Connect
	//	*AgentMessage_Ping
	//	*AgentMessage_State
	Payload              isAgentMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AgentMessage) Reset()         { *m = AgentMessage{} }
func (m *AgentMessage) String() string { return proto.CompactTextString(m) }
func (*AgentMessage) ProtoMessage()    {}
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{8}
}
func (m *AgentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMessage.Unmarshal(m, b)
}
func (m *AgentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMessage.Marshal(b, m, deterministic)
}
func (dst *AgentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMessage.Merge(dst, src)
}
func (m *AgentMessage) XXX_Size() int {
	return xxx_messageInfo_AgentMessage.Size(m)
}
func (m *AgentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMessage proto.InternalMessageInfo

func (m *AgentMessage) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,2,opt,name=connect,proto3,oneof"`
}

type AgentMessage_Ping struct {
	Ping *PingResponse `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type AgentMessage_State struct {
	State *SetStateResponse `protobuf:"bytes,4,opt,name=state,proto3,oneof"`
}

func (*AgentMessage_Connect) isAgentMessage_Payload() {}

func (*AgentMessage_Ping) isAgentMessage_Payload() {}

func (*AgentMessage_State) isAgentMessage_Payload() {}

func (m *AgentMessage) GetPayload() isAgentMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *AgentMessage) GetConnect() *ConnectRequest {
	if x, ok := m.GetPayload().(*AgentMessage_Connect); ok {
		return x.Connect
	}
	return nil
}

func (m *AgentMessage) GetPing() *PingResponse {
	if x, ok := m.GetPayload().(*AgentMessage_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *AgentMessage) GetState() *SetStateResponse {
	if x, ok := m.GetPayload().(*AgentMessage_State); ok {
		return x.State
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AgentMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AgentMessage_OneofMarshaler, _AgentMessage_OneofUnmarshaler, _AgentMessage_OneofSizer, []interface{}{
		(*AgentMessage_Connect)(nil),
		(*AgentMessage_Ping)(nil),
		(*AgentMessage_State)(nil),
	}
}

func _AgentMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AgentMessage)
	// payload
	switch x := m.Payload.(type) {
	case *AgentMessage_Connect:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Connect); err != nil {
			return err
		}
	case *AgentMessage_Ping:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ping); err != nil {
			return err
		}
	case *AgentMessage_State:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.State); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AgentMessage.Payload has unexpected type %T", x)
	}
	return nil
}

func _AgentMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AgentMessage)
	switch tag {
	case 2: // payload.connect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConnectRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &AgentMessage_Connect{msg}
		return true, err
	case 3: // payload.ping
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PingResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &AgentMessage_Ping{msg}
		return true, err
	case 4: // payload.state
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetStateResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &AgentMessage_State{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AgentMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AgentMessage)
	// payload
	switch x := m.Payload.(type) {
	case *AgentMessage_Connect:
		s := proto.Size(x.Connect)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AgentMessage_Ping:
		s := proto.Size(x.Ping)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AgentMessage_State:
		s := proto.Size(x.State)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ServerMessage struct {
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*ServerMessage_Connect
	//	*ServerMessage_Ping
	//	*ServerMessage_State
	Payload              isServerMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_00ef5a65756d40ea, []int{9}
}
func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (dst *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(dst, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Connect struct {
	Connect *ConnectResponse `protobuf:"bytes,2,opt,name=connect,proto3,oneof"`
}

type ServerMessage_Ping struct {
	Ping *PingRequest `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type ServerMessage_State struct {
	State *SetStateRequest `protobuf:"bytes,4,opt,name=state,proto3,oneof"`
}

func (*ServerMessage_Connect) isServerMessage_Payload() {}

func (*ServerMessage_Ping) isServerMessage_Payload() {}

func (*ServerMessage_State) isServerMessage_Payload() {}

func (m *ServerMessage) GetPayload() isServerMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ServerMessage) GetConnect() *ConnectResponse {
	if x, ok := m.GetPayload().(*ServerMessage_Connect); ok {
		return x.Connect
	}
	return nil
}

func (m *ServerMessage) GetPing() *PingRequest {
	if x, ok := m.GetPayload().(*ServerMessage_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *ServerMessage) GetState() *SetStateRequest {
	if x, ok := m.GetPayload().(*ServerMessage_State); ok {
		return x.State
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ServerMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ServerMessage_OneofMarshaler, _ServerMessage_OneofUnmarshaler, _ServerMessage_OneofSizer, []interface{}{
		(*ServerMessage_Connect)(nil),
		(*ServerMessage_Ping)(nil),
		(*ServerMessage_State)(nil),
	}
}

func _ServerMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ServerMessage)
	// payload
	switch x := m.Payload.(type) {
	case *ServerMessage_Connect:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Connect); err != nil {
			return err
		}
	case *ServerMessage_Ping:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ping); err != nil {
			return err
		}
	case *ServerMessage_State:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.State); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ServerMessage.Payload has unexpected type %T", x)
	}
	return nil
}

func _ServerMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ServerMessage)
	switch tag {
	case 2: // payload.connect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConnectResponse)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_Connect{msg}
		return true, err
	case 3: // payload.ping
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PingRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_Ping{msg}
		return true, err
	case 4: // payload.state
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SetStateRequest)
		err := b.DecodeMessage(msg)
		m.Payload = &ServerMessage_State{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ServerMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ServerMessage)
	// payload
	switch x := m.Payload.(type) {
	case *ServerMessage_Connect:
		s := proto.Size(x.Connect)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_Ping:
		s := proto.Size(x.Ping)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerMessage_State:
		s := proto.Size(x.State)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "agent.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "agent.RegisterResponse")
	proto.RegisterType((*ConnectRequest)(nil), "agent.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "agent.ConnectResponse")
	proto.RegisterType((*PingRequest)(nil), "agent.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "agent.PingResponse")
	proto.RegisterType((*SetStateRequest)(nil), "agent.SetStateRequest")
	proto.RegisterType((*SetStateResponse)(nil), "agent.SetStateResponse")
	proto.RegisterType((*AgentMessage)(nil), "agent.AgentMessage")
	proto.RegisterType((*ServerMessage)(nil), "agent.ServerMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Connect(ctx context.Context, opts ...grpc.CallOption) (Agent_ConnectClient, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Agent_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Agent_serviceDesc.Streams[0], "/agent.Agent/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentConnectClient{stream}
	return x, nil
}

type Agent_ConnectClient interface {
	Send(*AgentMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type agentConnectClient struct {
	grpc.ClientStream
}

func (x *agentConnectClient) Send(m *AgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentConnectClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Connect(Agent_ConnectServer) error
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).Connect(&agentConnectServer{stream})
}

type Agent_ConnectServer interface {
	Send(*ServerMessage) error
	Recv() (*AgentMessage, error)
	grpc.ServerStream
}

type agentConnectServer struct {
	grpc.ServerStream
}

func (x *agentConnectServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentConnectServer) Recv() (*AgentMessage, error) {
	m := new(AgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Agent_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Agent_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/agent.proto",
}

func init() { proto.RegisterFile("agent/agent.proto", fileDescriptor_agent_00ef5a65756d40ea) }

var fileDescriptor_agent_00ef5a65756d40ea = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x8e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0xe0, 0x60, 0x32, 0xf9, 0xbf, 0x40, 0x62, 0xb9, 0x01, 0xb9, 0x40, 0xa1, 0xb1,
	0xc1, 0x34, 0x48, 0x88, 0x48, 0x40, 0x93, 0x06, 0x09, 0x6d, 0x78, 0x01, 0x27, 0x99, 0xb3, 0x2c,
	0x25, 0x5e, 0x9f, 0x77, 0x1d, 0xe9, 0x9a, 0x7b, 0xae, 0x7b, 0xbc, 0x93, 0xf7, 0x8f, 0x13, 0x3b,
	0x77, 0xc5, 0x35, 0x96, 0x77, 0xf4, 0xcd, 0xec, 0xef, 0xfb, 0x76, 0x60, 0x16, 0x27, 0x98, 0x89,
	0x50, 0x7e, 0x83, 0xbc, 0x60, 0x82, 0x91, 0x9e, 0x3c, 0x78, 0x1f, 0x12, 0xc6, 0x92, 0x03, 0x86,
	0xb2, 0xb8, 0x2d, 0x6f, 0x42, 0x91, 0x1e, 0x91, 0x8b, 0xf8, 0x98, 0x2b, 0x9d, 0x3f, 0x83, 0x09,
	0xc5, 0x24, 0xe5, 0x02, 0x0b, 0x8a, 0xb7, 0x25, 0x72, 0xe1, 0x7f, 0x82, 0xe9, 0xb9, 0xc4, 0x73,
	0x96, 0x71, 0x24, 0x04, 0xec, 0xb2, 0x4c, 0xf7, 0xae, 0xf5, 0xd1, 0x5a, 0xf6, 0xa9, 0xfc, 0xf7,
	0x57, 0x30, 0xfe, 0xc3, 0xb2, 0x0c, 0x77, 0x42, 0x77, 0x3e, 0xa5, 0x22, 0x2e, 0x38, 0x27, 0x2c,
	0x78, 0xca, 0x32, 0xb7, 0x2b, 0xcb, 0xe6, 0x58, 0x5d, 0x5d, 0xf7, 0xab, 0x6b, 0xfc, 0x9f, 0x30,
	0xf8, 0x97, 0x66, 0x89, 0x99, 0x17, 0x80, 0x5d, 0xf1, 0xca, 0x79, 0x83, 0xc8, 0x0b, 0x94, 0x99,
	0xc0, 0x98, 0x09, 0xfe, 0x1b, 0x33, 0x54, 0xea, 0xfc, 0x15, 0x0c, 0x55, 0xbb, 0xa6, 0x7e, 0x69,
	0xff, 0x0c, 0x26, 0x1b, 0x14, 0x1b, 0x11, 0x0b, 0x34, 0x61, 0x10, 0x98, 0x9e, 0x4b, 0x9a, 0xf2,
	0xc1, 0x82, 0xe1, 0xaf, 0x2a, 0xde, 0xbf, 0xc8, 0x79, 0x9c, 0x20, 0x19, 0x43, 0x57, 0xbb, 0x1e,
	0xd1, 0x6e, 0xba, 0x27, 0x5f, 0xc1, 0xd9, 0x29, 0x67, 0xd2, 0xf3, 0x20, 0x7a, 0x1f, 0xa8, 0xb7,
	0x69, 0xe6, 0xb5, 0xee, 0x50, 0xa3, 0x23, 0x9f, 0xc1, 0xce, 0xd3, 0x2c, 0x71, 0x5f, 0x49, 0xfd,
	0x5b, 0xad, 0xbf, 0x74, 0xb3, 0xee, 0x50, 0x29, 0x21, 0x21, 0xf4, 0x78, 0xc5, 0xe3, 0xda, 0x52,
	0xbb, 0xd0, 0xda, 0x36, 0xe6, 0xba, 0x43, 0x95, 0xee, 0x77, 0x1f, 0x9c, 0x3c, 0xbe, 0x3b, 0xb0,
	0x78, 0x5f, 0xa1, 0x8f, 0x36, 0x58, 0x9c, 0xb0, 0x78, 0x8e, 0x3d, 0x6a, 0xb3, 0xcf, 0xdb, 0xec,
	0xf5, 0xf8, 0x1a, 0x7e, 0xd9, 0x80, 0x27, 0x0d, 0x78, 0xe3, 0x54, 0xb1, 0x07, 0x4d, 0xf6, 0xf9,
	0x15, 0xbb, 0x91, 0x5f, 0xa1, 0x47, 0xf7, 0xd0, 0x93, 0xa1, 0x93, 0x1f, 0xf0, 0xc6, 0xec, 0x27,
	0x31, 0x03, 0x5a, 0x3b, 0xec, 0x2d, 0xae, 0xea, 0x7a, 0x25, 0xbe, 0x83, 0xa3, 0x8d, 0x10, 0x13,
	0xf2, 0xe5, 0x53, 0x7a, 0xef, 0x6a, 0xa2, 0x8b, 0x90, 0x96, 0xd6, 0x17, 0x6b, 0xfb, 0x5a, 0xae,
	0xcd, 0xb7, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0xa6, 0x87, 0x0f, 0x6d, 0x03, 0x00, 0x00,
}
